### ISSUE TITLE
TODO: move to org

### ISSUE THREAD

**Issue by chriskrycho** [true-myth/true-myth#23]
Last week, I created a [parent org](https://github.com/true-myth) for True Myth implementations, since some colleagues are building out a C♯ translation. Let's migrate this there!

- [x] update package.json
- [x] update any references throughout docs
- [x] move the repo

**Comment by chriskrycho** [comment]
Done!
